### ISSUE TITLE
True / False are undefined (from @vit9696)

### ISSUE THREAD

**Issue by d0c-s4vage** [d0c-s4vage/py010parser#13]
courtesy of @vit9696 at https://github.com/d0c-s4vage/pfp/issues/28:

true and false keywords are unsupported by pfp.

**Comment by d0c-s4vage** [comment]
These are valid in 010 editor:

``` c
true
TRUE
false
FALSE
```

Pretty sure all that needs to be done is add some typedefs to the predefines.

**Comment by synalysis** [comment]
I've tested a bunch of binary templates I downloaded some while ago:
https://github.com/synalysis/pfp/blob/master/known_issues.md

Numerous formats would (maybe) work if true/false and other constants would be defined:
cLtGreen, cGreen, cLtGray, cLtRed, cRed, cLtAqua, cNone

The full list of colors can be found here: http://www.sweetscape.com/010editor/manual/FuncInterface.htm

**Comment by d0c-s4vage** [comment]
I'm not sure why I moved this issue into py010parser - definitely belongs in pfp. Closing and solving with  d0c-s4vage/pfp#28
